#!/usr/bin/env bash
# Write cloudflared config + install as systemd service.
# Run AFTER `cloudflared tunnel login` and `cloudflared tunnel create jobpulse`.
# Replace <UUID> below with the UUID printed by `cloudflared tunnel create`.

set -euo pipefail

TUNNEL_NAME="${TUNNEL_NAME:-jobpulse}"
TUNNEL_UUID="${TUNNEL_UUID:-<UUID>}"   # ← replace with real UUID before running
CREDS_FILE="/home/jobpulse/.cloudflared/${TUNNEL_UUID}.json"
CONFIG_FILE="/etc/cloudflared/config.yml"

if [[ "$TUNNEL_UUID" == "<UUID>" ]]; then
    echo "ERROR: edit this script and replace <UUID> with the actual tunnel UUID." >&2
    echo "Run: cloudflared tunnel create $TUNNEL_NAME" >&2
    echo "Then: sed -i 's/<UUID>/<actual-uuid>/' $0" >&2
    exit 1
fi

if [[ ! -f "$CREDS_FILE" ]]; then
    echo "ERROR: credentials file not found at $CREDS_FILE" >&2
    echo "Did you run 'cloudflared tunnel login' and 'cloudflared tunnel create $TUNNEL_NAME'?" >&2
    exit 1
fi

cat > "$CONFIG_FILE" <<EOF
# JobPulse Cloudflare Tunnel
# Auto-generated by deploy/scripts/install-cloudflared.sh

tunnel: $TUNNEL_UUID
credentials-file: $CREDS_FILE

# Log to journald
logfile: /var/log/cloudflared.log
loglevel: info

# Free trycloudflare.com subdomain. Replace with your own hostname later.
ingress:
  - hostname: ""
    service: http://127.0.0.1:80
  - service: http_status:404
EOF

chmod 600 "$CONFIG_FILE"
echo "wrote $CONFIG_FILE"

# Install as systemd service
cloudflared service install
systemctl enable cloudflared
systemctl restart cloudflared
echo "cloudflared installed and started. Watch logs: journalctl -u cloudflared -f"
